### ISSUE TITLE
DDC build doesn't work ?

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/bazel#163]
Create a minimal package (pubspec + web/index_ddc_bundle.html + web/index.dart+ analysis_options.yaml ), run `pub run dazel init` and `pub run dazel build web/index_ddc_bundle.html`), the build fails with the following error:

`Invalid argument(s): AnalysisContext must be strong mode`

Adding `--strategy=DartDevCompiler=standalone` to `.bazelrc` make it go further but it fails on another error : 

`FileSystemException: Cannot open file, path = 'bazel-bin/web/index.dart.js.tar' (OS Error: No such file or directory, errno = 2)`

**Comment by jakemac53** [comment]
Hmm, I am not getting this error (although I am getting an error related to summaries).

Note however that the `dazel build` command is meant to run dart2js, not ddc. Providing it the ddc html file like that will not work.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/rules_dart/pull/121 should fix the analyzer summary issue I was running into, once we make bazel point at that release.

**Comment by dam0vm3nt** [comment]
Ah ok. I tried to figure it out from the BUILD file. What's the right way to build a package with ddc then and should the package structure be different from the minimal sample above?

**Comment by jakemac53** [comment]
Deploying with DDC isn't supported today, just serving (via `pub run dazel serve`).

The main difference there is we won't synthesize a `build` directory for you out of the outputs, you would have to go digging in bazel-bin etc.

Feel free to open a separate issue about enabling a ddc mode for deployment though, possibly just adding a `--ddc` flag to the `pub run dazel build` command?

**Comment by dam0vm3nt** [comment]
That would be great. Ok. Closing this for now if you agree.

Il Lun 20 Mar 2017, 16:30 Jacob MacDonald <notifications@github.com> ha
scritto:

**Comment by jakemac53** [comment]
Yep, just published a new version as well so `serve` should work properly with ddc now.
