### ISSUE TITLE
Need support for Builder chains that have 'side' outputs

### ISSUE THREAD

**Issue by natebosch** [dart-lang/bazel#172]
Today we only feed a Builder's outputs as inputs into the next Builder. This is handy for the case where you have a multistep transformation, but disallows the case where a single input get's multiple outputs - but those outputs need to happen sequentially.

I had designed this limitation since originally there were no use cases for chains for builders that didn't follow this pattern, and I wanted to limit the config.

It might be possible to simply collect inputs as we go, so that future steps see everything from before. If this won't work we'll probably have to push forward with the idea that a `Builder` specifies input and output extensions...

**Comment by natebosch** [comment]
cc @jakemac53 

I think we're going to have to push forward quickly on https://github.com/dart-lang/build/issues/222

Otherwise I think we'd either need to add back more fine grained extension config and a `Phase` concept, or enforce that all `Builder` implementations can tolerate getting inputs of the wrong extension.

**Comment by jakemac53** [comment]
I like the idea of just having the inputExtension/outputExtension fields.

This does get a bit interesting for the glob case though?

**Comment by natebosch** [comment]
This isn't meant to support the full `Phase` from `build_runner`, so I don't think we need to worry about globs.

**Comment by jakemac53** [comment]
If you think about something like dev_compiler long term, this may become problematic. It will need to run based on a single entry point in a package, but have multiple js file outputs (one for each module it decides to create). I don't know how that would be expressed.

**Comment by natebosch** [comment]
Hmm, for the dev_compiler case we might need something like an AggregateBuilder...

Do you think the input/output extension change makes dev_compiler harder?

**Comment by jakemac53** [comment]
Actually no I don't think it really does... it is a more general issue. Declaring outputs at all is going to be interesting if we want more than one module per package.
