### ISSUE TITLE
Lint for excluding bazel-* from the analyzer

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/bazel#21]
Otherwise you easily get 20000+ analyzer issues as it recurses deep.

/cc @kevmoo - this can almost crash your system. Can analysis server team auto-exclude?

**Comment by bwilkerson** [comment]
I don't think we need special handling for these directories. They will be ignored if the user opens a subdirectory of the root workspace directory, and I think that should be our advice. (https://github.com/dart-lang/bazel/issues/32)
