### ISSUE TITLE
Pub global activate does not add executable bazel

### ISSUE THREAD

**Issue by mswift42** [dart-lang/bazel#45]
if I run pub global activate bazel:

> pub global activate bazel    
> Package bazel is currently active at version 0.1.0.
> Resolving dependencies... (3.0s)
> + args 0.13.6
> + bazel 0.1.0
> + charcode 1.1.0
> + collection 1.9.1
> + meta 1.0.4
> + package_config 1.0.0
> + path 1.4.0
> + source_span 1.2.4
> + stack_trace 1.6.8
> + string_scanner 1.0.0
> + when 0.2.0
> + which 0.1.3
> + yaml 2.1.12
> Precompiling executables... 
> Loading source assets... 
> Precompiled bazel:bazelify.
> Activated bazel 0.1.0.
> Installed executable bazelify.

I can not run bazelify, because:

>  bazelify 
> Unhandled exception:
> Bad state: Command not found: bazel
> 

This happens on ubuntu 16.04.

**Comment by natebosch** [comment]
What is your PATH?

When you run pub global activate it should warn you that it's bin directory is missing from your path.

>Warning: Pub installs executables into ~/.pub-cache/bin, which is not on your path.
>You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):
>
 >export PATH="$PATH":"~/.pub-cache/bin"

Are you able to run executables after pub global activate for any other packages?

**Comment by mswift42** [comment]
The only pub global activate packages I've installed are stagehand, which works, and now bazel. 

The thing is, I now have the executable bazelify:

> which bazelify
> /home/martin/.pub-cache/bin/bazelify

But running bazelify complains about command not found bazel.

**Comment by natebosch** [comment]
ah I see the issue - our names are really confusing.

package:bazel does not provide the command bazel. It's a collection of Dart utilities around bazel which is a separate project - see www.bazel.io

The naming is especially confusing when our collection contains a single utility - bazelify.

I'll update the README to make this more clear

**Comment by mswift42** [comment]
OK, installed bazel from bazel.io, it's working now :)

**Comment by matanlurey** [comment]
Bazel is a build tool that our bazel package runs with. You need the (Java)
program "Bazel" installed. See the README.md please.

**Comment by matanlurey** [comment]
That error looks like you don't have bazel itself installed which is a
perquisite. See README.md.
