### ISSUE TITLE
Bazelify a dart angular 2 polymer project

### ISSUE THREAD

**Issue by invader35** [dart-lang/bazel#61]
I tried to bazelify a small project (https://github.com/montyr75/tictactoe), but i always encounter the following error message:

`> bazelify init`
`
Error on line 198, column 1: Duplicate mapping key.
environment:
^^^^^^^^^^^
package:yaml/src/loader.dart 160                Loader._loadMapping
package:yaml/src/loader.dart 82                 Loader._loadNode
package:yaml/src/loader.dart 62                 Loader._loadDocument
package:yaml/src/loader.dart 54                 Loader.load
package:yaml/yaml.dart 51                       loadYamlDocument
package:yaml/yaml.dart 42                       loadYamlNode
package:yaml/yaml.dart 34                       loadYaml
package:bazel/src/bazelify/pubspec.dart 26      Pubspec.Pubspec.parse
package:bazel/src/bazelify/pubspec.dart 18      Pubspec.fromPackageDir.<async>
===== asynchronous gap ===========================
dart:async                                      _Completer.completeError
package:bazel/src/bazelify/pubspec.dart 23      Pubspec.fromPackageDir.<async>
===== asynchronous gap ===========================
dart:async                                      _asyncThenWrapperHelper
package:bazel/src/bazelify/pubspec.dart         Pubspec.fromPackageDir
package:bazel/src/bazelify/build.dart 76        BuildFile.fromPackageDir.<async>
===== asynchronous gap ===========================
dart:async                                      Future.Future.microtask
package:bazel/src/bazelify/build.dart           BuildFile.fromPackageDir
package:bazel/src/bazelify/initialize.dart 233  initalize.<async>
===== asynchronous gap ===========================
dart:async                                      _asyncThenWrapperHelper
package:bazel/src/bazelify/initialize.dart      initalize
package:bazel/src/bazelify/initialize.dart 132  InitCommand.run.<async>
===== asynchronous gap ===========================
dart:async                                      _asyncThenWrapperHelper
package:bazel/src/bazelify/initialize.dart      InitCommand.run
package:args/command_runner.dart 183            CommandRunner.runCommand.<fn>
dart:async                                      Future.Future.sync
package:args/command_runner.dart 136            CommandRunner.runCommand
package:args/command_runner.dart 105            CommandRunner.run.<fn>
dart:async                                      Future.Future.sync
package:args/command_runner.dart 105            CommandRunner.run
http://localhost:38484/bazelify.dart 12         main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                             Chain.capture
http://localhost:38484/bazelify.dart 11         main.<async>
`

**Comment by matanlurey** [comment]
Would you mind posting your `pubspec.lock` file?

**Comment by invader35** [comment]
Ah okay, here is my pubspec.lock file:


[pubspec.lock.txt](https://github.com/dart-lang/bazel/files/564640/pubspec.lock.txt)

**Comment by matanlurey** [comment]
@invader35 Yup, this is due to [polymer_elements](https://pub.dartlang.org/packages/polymer_elements) having the `environment:` key specified twice, which is invalid YAML :-/

**Comment by invader35** [comment]
@matanlurey Thanks for the info, i will create an issue in polymer_elements although it seems unsupported.

**Comment by jakemac53** [comment]
A fix for this was recently merged into polymer_elements, but a version hasn't been published with that change. You could use a git dependency on polymer_elements to work around that today.

**Comment by invader35** [comment]
@jakemac53 Thans for the information, i will your advice and if it works i will close this issue.
Thx also to @matanlurey  for the fast response

**Comment by invader35** [comment]
With the depdency on the github repo directly, it works.
Thx again for the help
