### ISSUE TITLE
Modify bazel tasks

### ISSUE THREAD

**Issue by Aetet** [dart-lang/bazel#66]
Is it possible to create my own tasks for generated in addition for existent in bazel file? How to solve this issue?

**Comment by natebosch** [comment]
Once we solve https://github.com/dart-lang/bazel/issues/12 it will be easier to manually add/change build steps.

You can do this today if you only run `bazelify init` once, then manually edit the BUILD file. Running the init again would overwrite your changes today.

**Comment by Aetet** [comment]
Ok. Thanks.
