### ISSUE TITLE
main_ddc_serve - ERROR: no such target

### ISSUE THREAD

**Issue by avstudios** [dart-lang/bazel#82]
Not sure what I'm doing wrong. I  have a simple project generated by ```stagehand web-simple``` command. I've also run ```bazelify init```.  And when I type ```bazel build :main_ddc_serve``` I'm getting an error:

```ERROR: no such target '//:main_ddc_serve': target 'main_ddc_serve' not declared in package '' defined by my_project/BUILD.```

**Comment by nshahan** [comment]
I believe the documentation didn't get updated from some changes that were made and the build targets now have different names. Take a peek in the `BUILD` file that was created by `bazelify init` if you are curious about their names. You should be able to build with `bazel build :index_ddc_bundle` or serve with the command `bazelify serve`.

This repo is still in an experimental phase so this stuff is subject to change. We will try to keep the documentation updated though.

**Comment by avstudios** [comment]
Great, it's what I needed. Thanks.
